FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY ./ ./

RUN dotnet restore "Application/Application.csproj"

RUN dotnet build "Application/Application.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Application/Application.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

COPY --from=publish /app/publish .

EXPOSE 7262
EXPOSE 5183

ENTRYPOINT ["dotnet", "Application.dll"]