FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY . ./

RUN dotnet restore "SberHackathonBack.sln"
RUN dotnet build "SberHackathonBack.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SberHackathonBack.sln" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app

COPY --from=publish /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Presentation.dll"]